theme: jekyll-theme-slate
google_site_verification: D5ixU_08KXu4tDMaycnskWkUtkC3kO5oKSb6NTsfXPE

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/audiopick-preview-890x890.png
